// Common materials used in GSO (General Services Office) maintenance and repair work
// Organized by category for easy browsing

export const COMMON_MATERIALS = [
  // Plumbing & Pipe Fittings
  { name: 'PVC Pipe 1/2 inch', category: 'Plumbing', unit: 'lengths' },
  { name: 'PVC Pipe 3/4 inch', category: 'Plumbing', unit: 'lengths' },
  { name: 'PVC Pipe 1 inch', category: 'Plumbing', unit: 'lengths' },
  { name: 'PVC Elbow 1/2 inch', category: 'Plumbing', unit: 'pcs' },
  { name: 'PVC Elbow 3/4 inch', category: 'Plumbing', unit: 'pcs' },
  { name: 'PVC Tee 1/2 inch', category: 'Plumbing', unit: 'pcs' },
  { name: 'PVC Coupling 1/2 inch', category: 'Plumbing', unit: 'pcs' },
  { name: 'PVC Union 1/2 inch', category: 'Plumbing', unit: 'pcs' },
  { name: 'PVC Cement (Solvent)', category: 'Plumbing', unit: 'cans' },
  { name: 'Teflon Tape', category: 'Plumbing', unit: 'rolls' },
  { name: 'Gate Valve 1/2 inch', category: 'Plumbing', unit: 'pcs' },
  { name: 'Gate Valve 3/4 inch', category: 'Plumbing', unit: 'pcs' },
  { name: 'Ball Valve 1/2 inch', category: 'Plumbing', unit: 'pcs' },
  { name: 'Faucet (Lavatory)', category: 'Plumbing', unit: 'pcs' },
  { name: 'Faucet (Kitchen)', category: 'Plumbing', unit: 'pcs' },
  { name: 'Angle Valve 1/2 inch', category: 'Plumbing', unit: 'pcs' },
  { name: 'Flexible Hose 1/2 inch', category: 'Plumbing', unit: 'pcs' },
  { name: 'P-Trap (Lavatory)', category: 'Plumbing', unit: 'pcs' },
  { name: 'Floor Drain 4x4', category: 'Plumbing', unit: 'pcs' },
  { name: 'Cleanout Plug', category: 'Plumbing', unit: 'pcs' },

  // Electrical
  { name: 'THHN Wire #12 (3.5mm²)', category: 'Electrical', unit: 'meters' },
  { name: 'THHN Wire #10 (5.5mm²)', category: 'Electrical', unit: 'meters' },
  { name: 'THHN Wire #14 (2.0mm²)', category: 'Electrical', unit: 'meters' },
  { name: 'PDX Wire #12', category: 'Electrical', unit: 'meters' },
  { name: 'PDX Wire #14', category: 'Electrical', unit: 'meters' },
  { name: 'PVC Conduit 1/2 inch', category: 'Electrical', unit: 'lengths' },
  { name: 'PVC Conduit 3/4 inch', category: 'Electrical', unit: 'lengths' },
  { name: 'PVC Conduit 1 inch', category: 'Electrical', unit: 'lengths' },
  { name: 'PVC Elbow 1/2 inch (Electrical)', category: 'Electrical', unit: 'pcs' },
  { name: 'PVC Coupling 1/2 inch (Electrical)', category: 'Electrical', unit: 'pcs' },
  { name: 'Junction Box 4x4', category: 'Electrical', unit: 'pcs' },
  { name: 'Utility Box 2x4', category: 'Electrical', unit: 'pcs' },
  { name: 'Switch (Single Pole)', category: 'Electrical', unit: 'pcs' },
  { name: 'Switch (3-Way)', category: 'Electrical', unit: 'pcs' },
  { name: 'Outlet (Duplex)', category: 'Electrical', unit: 'pcs' },
  { name: 'Outlet (GFCI)', category: 'Electrical', unit: 'pcs' },
  { name: 'Circuit Breaker 20A', category: 'Electrical', unit: 'pcs' },
  { name: 'Circuit Breaker 30A', category: 'Electrical', unit: 'pcs' },
  { name: 'Circuit Breaker 60A', category: 'Electrical', unit: 'pcs' },
  { name: 'Electrical Tape', category: 'Electrical', unit: 'rolls' },
  { name: 'Wire Nut (Assorted)', category: 'Electrical', unit: 'pcs' },
  { name: 'LED Bulb 9W', category: 'Electrical', unit: 'pcs' },
  { name: 'LED Bulb 12W', category: 'Electrical', unit: 'pcs' },
  { name: 'LED Bulb 18W', category: 'Electrical', unit: 'pcs' },
  { name: 'LED Tube 18W (T8)', category: 'Electrical', unit: 'pcs' },
  { name: 'LED Panel Light 12W', category: 'Electrical', unit: 'pcs' },
  { name: 'LED Panel Light 18W', category: 'Electrical', unit: 'pcs' },
  { name: 'Starter (Fluorescent)', category: 'Electrical', unit: 'pcs' },
  { name: 'Ballast (Electronic)', category: 'Electrical', unit: 'pcs' },
  { name: 'Exhaust Fan', category: 'Electrical', unit: 'pcs' },
  { name: 'Ceiling Fan', category: 'Electrical', unit: 'pcs' },
  { name: 'Capacitor (Fan)', category: 'Electrical', unit: 'pcs' },

  // Carpentry & Hardware
  { name: 'Marine Plywood 1/4 inch', category: 'Carpentry', unit: 'sheets' },
  { name: 'Marine Plywood 1/2 inch', category: 'Carpentry', unit: 'sheets' },
  { name: 'Marine Plywood 3/4 inch', category: 'Carpentry', unit: 'sheets' },
  { name: 'Ordinary Plywood 1/4 inch', category: 'Carpentry', unit: 'sheets' },
  { name: 'Gypsum Board 1/2 inch', category: 'Carpentry', unit: 'sheets' },
  { name: 'Metal Studs', category: 'Carpentry', unit: 'lengths' },
  { name: 'Metal Tracks', category: 'Carpentry', unit: 'lengths' },
  { name: 'Wood Screw 1 inch', category: 'Carpentry', unit: 'boxes' },
  { name: 'Wood Screw 1-1/2 inch', category: 'Carpentry', unit: 'boxes' },
  { name: 'Wood Screw 2 inch', category: 'Carpentry', unit: 'boxes' },
  { name: 'Black Screw 1 inch', category: 'Carpentry', unit: 'boxes' },
  { name: 'Black Screw 1-1/2 inch', category: 'Carpentry', unit: 'boxes' },
  { name: 'Concrete Nail 1 inch', category: 'Carpentry', unit: 'kg' },
  { name: 'Concrete Nail 2 inch', category: 'Carpentry', unit: 'kg' },
  { name: 'Common Nail 1 inch', category: 'Carpentry', unit: 'kg' },
  { name: 'Common Nail 2 inch', category: 'Carpentry', unit: 'kg' },
  { name: 'Common Nail 3 inch', category: 'Carpentry', unit: 'kg' },
  { name: 'Door Knob (Lockset)', category: 'Carpentry', unit: 'pcs' },
  { name: 'Door Hinge 3x3', category: 'Carpentry', unit: 'pairs' },
  { name: 'Door Hinge 4x4', category: 'Carpentry', unit: 'pairs' },
  { name: 'Cabinet Hinge', category: 'Carpentry', unit: 'pairs' },
  { name: 'Drawer Slide', category: 'Carpentry', unit: 'pairs' },
  { name: 'Door Closer', category: 'Carpentry', unit: 'pcs' },
  { name: 'Barrel Bolt', category: 'Carpentry', unit: 'pcs' },
  { name: 'Padlock', category: 'Carpentry', unit: 'pcs' },

  // Masonry & Concrete
  { name: 'Portland Cement', category: 'Masonry', unit: 'bags' },
  { name: 'Sand (Washed)', category: 'Masonry', unit: 'cu.m.' },
  { name: 'Gravel 3/4', category: 'Masonry', unit: 'cu.m.' },
  { name: 'CHB 4 inch', category: 'Masonry', unit: 'pcs' },
  { name: 'CHB 6 inch', category: 'Masonry', unit: 'pcs' },
  { name: 'Rebar 10mm', category: 'Masonry', unit: 'lengths' },
  { name: 'Rebar 12mm', category: 'Masonry', unit: 'lengths' },
  { name: 'Tie Wire #16', category: 'Masonry', unit: 'kg' },
  { name: 'Tile Adhesive', category: 'Masonry', unit: 'bags' },
  { name: 'Tile Grout', category: 'Masonry', unit: 'bags' },
  { name: 'Floor Tile 60x60', category: 'Masonry', unit: 'pcs' },
  { name: 'Wall Tile 30x60', category: 'Masonry', unit: 'pcs' },
  { name: 'Waterproofing Membrane', category: 'Masonry', unit: 'gallons' },
  { name: 'Concrete Neutralizer', category: 'Masonry', unit: 'gallons' },

  // Painting
  { name: 'Flat Latex Paint (White)', category: 'Painting', unit: 'gallons' },
  { name: 'Semi-Gloss Latex Paint (White)', category: 'Painting', unit: 'gallons' },
  { name: 'Gloss Latex Paint (White)', category: 'Painting', unit: 'gallons' },
  { name: 'Flat Latex Paint (Tinted)', category: 'Painting', unit: 'gallons' },
  { name: 'QDE Paint (White)', category: 'Painting', unit: 'gallons' },
  { name: 'QDE Paint (Tinted)', category: 'Painting', unit: 'gallons' },
  { name: 'Primer (Red Oxide)', category: 'Painting', unit: 'gallons' },
  { name: 'Primer (White)', category: 'Painting', unit: 'gallons' },
  { name: 'Paint Thinner', category: 'Painting', unit: 'gallons' },
  { name: 'Paint Roller 7 inch', category: 'Painting', unit: 'pcs' },
  { name: 'Paint Roller 9 inch', category: 'Painting', unit: 'pcs' },
  { name: 'Paint Brush 2 inch', category: 'Painting', unit: 'pcs' },
  { name: 'Paint Brush 3 inch', category: 'Painting', unit: 'pcs' },
  { name: 'Baby Roller 4 inch', category: 'Painting', unit: 'pcs' },
  { name: 'Putty Knife', category: 'Painting', unit: 'pcs' },
  { name: 'Sandpaper #100', category: 'Painting', unit: 'pcs' },
  { name: 'Sandpaper #120', category: 'Painting', unit: 'pcs' },
  { name: 'Sandpaper #180', category: 'Painting', unit: 'pcs' },
  { name: 'Body Filler', category: 'Painting', unit: 'kg' },
  { name: 'Polyester Putty', category: 'Painting', unit: 'kg' },

  // Roofing
  { name: 'Pre-Painted Long Span (Rib Type)', category: 'Roofing', unit: 'meters' },
  { name: 'Pre-Painted Long Span (Corrugated)', category: 'Roofing', unit: 'meters' },
  { name: 'Ridge Roll', category: 'Roofing', unit: 'pcs' },
  { name: 'Flashing', category: 'Roofing', unit: 'pcs' },
  { name: 'Gutter (Pre-Painted)', category: 'Roofing', unit: 'meters' },
  { name: 'Downspout (Pre-Painted)', category: 'Roofing', unit: 'meters' },
  { name: 'Tek Screw 2 inch', category: 'Roofing', unit: 'boxes' },
  { name: 'Sealant (Roof)', category: 'Roofing', unit: 'tubes' },
  { name: 'Vulca Seal', category: 'Roofing', unit: 'liters' },

  // Welding & Metal Works
  { name: 'Welding Rod 6013 (1/8)', category: 'Welding', unit: 'kg' },
  { name: 'Welding Rod 7018 (1/8)', category: 'Welding', unit: 'kg' },
  { name: 'Cutting Disc 4 inch', category: 'Welding', unit: 'pcs' },
  { name: 'Grinding Disc 4 inch', category: 'Welding', unit: 'pcs' },
  { name: 'Angle Bar 1/4 x 1 x 1', category: 'Welding', unit: 'lengths' },
  { name: 'Angle Bar 1/4 x 1-1/2 x 1-1/2', category: 'Welding', unit: 'lengths' },
  { name: 'Angle Bar 3/16 x 2 x 2', category: 'Welding', unit: 'lengths' },
  { name: 'Flat Bar 1/4 x 1', category: 'Welding', unit: 'lengths' },
  { name: 'Flat Bar 1/4 x 2', category: 'Welding', unit: 'lengths' },
  { name: 'Round Bar 10mm', category: 'Welding', unit: 'lengths' },
  { name: 'Round Bar 12mm', category: 'Welding', unit: 'lengths' },
  { name: 'Square Bar 12mm', category: 'Welding', unit: 'lengths' },
  { name: 'GI Pipe 1/2 inch (Sched 40)', category: 'Welding', unit: 'lengths' },
  { name: 'GI Pipe 3/4 inch (Sched 40)', category: 'Welding', unit: 'lengths' },
  { name: 'GI Pipe 1 inch (Sched 40)', category: 'Welding', unit: 'lengths' },
  { name: 'GI Pipe 2 inch (Sched 40)', category: 'Welding', unit: 'lengths' },

  // Aircon & Refrigeration
  { name: 'Copper Tube 1/4 inch', category: 'Aircon', unit: 'meters' },
  { name: 'Copper Tube 3/8 inch', category: 'Aircon', unit: 'meters' },
  { name: 'Copper Tube 1/2 inch', category: 'Aircon', unit: 'meters' },
  { name: 'Copper Tube 5/8 inch', category: 'Aircon', unit: 'meters' },
  { name: 'Flare Nut 1/4 inch', category: 'Aircon', unit: 'pcs' },
  { name: 'Flare Nut 3/8 inch', category: 'Aircon', unit: 'pcs' },
  { name: 'Flare Nut 1/2 inch', category: 'Aircon', unit: 'pcs' },
  { name: 'Flare Nut 5/8 inch', category: 'Aircon', unit: 'pcs' },
  { name: 'Refrigerant R-410A', category: 'Aircon', unit: 'kg' },
  { name: 'Refrigerant R-32', category: 'Aircon', unit: 'kg' },
  { name: 'Refrigerant R-22', category: 'Aircon', unit: 'kg' },
  { name: 'Capacitor (Aircon) 45+5 uF', category: 'Aircon', unit: 'pcs' },
  { name: 'Capacitor (Aircon) 50+5 uF', category: 'Aircon', unit: 'pcs' },
  { name: 'Capacitor (Aircon) 60+5 uF', category: 'Aircon', unit: 'pcs' },
  { name: 'Fan Motor (Indoor)', category: 'Aircon', unit: 'pcs' },
  { name: 'Fan Motor (Outdoor)', category: 'Aircon', unit: 'pcs' },
  { name: 'PCB Board (Aircon)', category: 'Aircon', unit: 'pcs' },
  { name: 'Drain Pump', category: 'Aircon', unit: 'pcs' },
  { name: 'Insulation Tape (Rubber)', category: 'Aircon', unit: 'rolls' },
  { name: 'PE Foam Insulation 1/2 inch', category: 'Aircon', unit: 'meters' },

  // General Supplies & Consumables
  { name: 'Silicone Sealant (Clear)', category: 'General', unit: 'tubes' },
  { name: 'Silicone Sealant (White)', category: 'General', unit: 'tubes' },
  { name: 'Construction Adhesive', category: 'General', unit: 'tubes' },
  { name: 'Epoxy A & B', category: 'General', unit: 'sets' },
  { name: 'Contact Cement', category: 'General', unit: 'cans' },
  { name: 'Rugby (Contact Cement)', category: 'General', unit: 'cans' },
  { name: 'Masking Tape 1 inch', category: 'General', unit: 'rolls' },
  { name: 'Masking Tape 2 inch', category: 'General', unit: 'rolls' },
  { name: 'Duct Tape', category: 'General', unit: 'rolls' },
  { name: 'Caution Tape', category: 'General', unit: 'rolls' },
  { name: 'Sand (Plastering)', category: 'General', unit: 'bags' },
  { name: 'Cement (Plastering)', category: 'General', unit: 'bags' },
  { name: 'Gypsum Putty', category: 'General', unit: 'kg' },
  { name: 'Steel Wool', category: 'General', unit: 'packs' },
  { name: 'Wire Brush', category: 'General', unit: 'pcs' },
  { name: 'Putty Knife 2 inch', category: 'General', unit: 'pcs' },
  { name: 'Putty Knife 4 inch', category: 'General', unit: 'pcs' },
  { name: 'Hacksaw Blade', category: 'General', unit: 'pcs' },
  { name: 'Drill Bit 1/8 (Metal)', category: 'General', unit: 'pcs' },
  { name: 'Drill Bit 3/16 (Metal)', category: 'General', unit: 'pcs' },
  { name: 'Drill Bit 1/4 (Metal)', category: 'General', unit: 'pcs' },
  { name: 'Drill Bit 3/8 (Concrete)', category: 'General', unit: 'pcs' },
  { name: 'Drill Bit 1/2 (Concrete)', category: 'General', unit: 'pcs' },
  { name: 'Tox #6', category: 'General', unit: 'pcs' },
  { name: 'Tox #8', category: 'General', unit: 'pcs' },
  { name: 'Tox #10', category: 'General', unit: 'pcs' },
  { name: 'Screw 1/2 inch (Metal)', category: 'General', unit: 'boxes' },
  { name: 'Screw 3/4 inch (Metal)', category: 'General', unit: 'boxes' },
  { name: 'Screw 1 inch (Metal)', category: 'General', unit: 'boxes' },
];

// Helper to get unique categories
export const MATERIAL_CATEGORIES = [...new Set(COMMON_MATERIALS.map(m => m.category))].sort();

// Helper to get materials by category
export const getMaterialsByCategory = (category) => {
  return COMMON_MATERIALS.filter(m => m.category === category);
};

// Helper to get all material names (for datalist/autocomplete)
export const ALL_MATERIAL_NAMES = COMMON_MATERIALS.map(m => m.name).sort();

// Helper to get material info by name
export const getMaterialInfo = (name) => {
  return COMMON_MATERIALS.find(m => m.name.toLowerCase() === name.toLowerCase());
};

// Helper to get default unit for a material
export const getDefaultUnit = (materialName) => {
  const material = getMaterialInfo(materialName);
  return material?.unit || 'pcs';
};